### ISSUE TITLE
amd gpu requirements? RX550 and RX Vega hang and not working

### ISSUE THREAD

**Issue by muiaao** [zpminer/zpminer#3]
WIn10 LTSB release 160715-1616
Driver: AMD Adrenalin 18.4.1

Motherboardand etc: : Asus Z170+G3930+4gb DDR4 ram
GPU: XFX RX550 2GB   
         XFX RX Vega64 ref.

Monitor connected to GPU.

command line: zpminer.exe WALLET u=stratum+tcp:\\zp-us-east.leafpool.com:8822

when run miner.bat including above command line only, no error pops (or too fast before black out) spotted. 

System freezes after like 5 senconds, screen on and off for several times, then totally hangs. Had to unplug PSU.  GPU card seems to be very hot.

System is fresh installed.

**Comment by zpminer** [comment]
Please try to run it on a command window that's open rather than clicking a batch file, so that you can see the error that is reported before it exits. Or, you can add a 'pause' line to your batch file too, so that the window doesn't close on you.

There's a chance your GPU is on platform other than the default 0. You can try p=1 if your GPU is on platform 1 instead of 0. Often, if you have a motherboard integrated graphics card that will take the p=0 slot and your GPU card will be on p=1

If you want to use leafpool, you'll need to use // instead of \ like this:
u=stratum+tcp://zp-us-east.leafpool.com:8822

You can also try without the u= argument. It defaults to pandapool.
